In [5]:
import numpy as np
import pandas as pd

In [7]:
def calculate_bmi(weight, height): # define new function and its parameters
    bmi = weight / (height * 2) # declare the formulae given
    if bmi < 18.5:
        category = "underweight"
    elif 18.5 <= bmi < 24.9:
        category = "normal"
    elif 25 <= bmi < 29.9:
        category = "overweight"
    else:
        category = "obese"

In [9]:
def extract_year(matric_number): # define what we want to do (function)
    return matric_number[3:7] # only return index from 3 until before 7

In [11]:
def check_faculty(matric_number):
    return matric_number.startwith("MAT") # only return if it's from math faculty

In [13]:
def generate_matric_number(fac, year, student_id):
    return f"{fac}{year}{student_id:04d}" # 04d is a 4-digit unique number 

In [15]:
def find_length(story):  # we use 'story' as parameter
    return len(story)

text = "Once upon a time, in a land far away, there lived a young programmer who loved to solve problems. He spent his days learning Python and exploring the secrets of code."
print (find_length(text)) # we use 'text' as argument

166


In [17]:
position = text.find("Python")
print(position)

125


In [21]:
text = "Once upon a time, in a land far away, there lived a young programmer who loved to solve problems. He spent his days learning Python and exploring the secrets of code."

def extract_string(story):
    return story[5:16]

print(extract_string(text))

upon a time


In [23]:
text = "Once upon a time, in a land far away, there lived a young programmer who loved to solve problems. He spent his days learning Python and exploring the secrets of code."

def extract_substring(story):
    return story[38:95]

print(extract_substring(text))

there lived a young programmer who loved to solve problem


In [27]:
text = "Once upon a time, in a land far away, there lived a young programmer who loved to solve problems. He spent his days learning Python and exploring the secrets of code."
print(text[::-1])

.edoc fo sterces eht gnirolpxe dna nohtyP gninrael syad sih tneps eH .smelborp evlos ot devol ohw remmargorp gnuoy a devil ereht ,yawa raf dnal a ni ,emit a nopu ecnO


In [29]:
average = lambda x, y, z: (x + y + z)/3 # average is the name of the function
result = average(10, 20, 30)
print(result)

20.0


In [35]:
data = ((1, "Alice", 25), (2, "Bob", 30), (3, "Charlie", 35))
print(data[2])

(3, 'Charlie', 35)


In [41]:
data = ((1, "Alice", 25), (2, "Bob", 30), (3, "Charlie", 35))

length = len(data)
print(length)

3


In [45]:
info = 2, "Bob", 30

id, name, age = info

print("Name :", name)
print("ID :", id)
print("Age :", age)

Name : Bob
ID : 2
Age : 30


In [51]:
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]

list3 = list1 + list2 

print(list3)

[1, 2, 3, 4, 5, 6, 7, 8]


In [53]:
list3.append(9)
print(list3)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [55]:
import numpy as np

random_array = np.random.randint(1, 101, size=30)
print(random_array)

[98 89 17 71 87 34 20 92 63 87 62 60 89 79 28 97 44 79 79 93  9  2 59 65
 22 23  5 98 41 90]


In [59]:
reshaped_array = random_array.reshape(5, 6)
print(reshaped_array)

[[98 89 17 71 87 34]
 [20 92 63 87 62 60]
 [89 79 28 97 44 79]
 [79 93  9  2 59 65]
 [22 23  5 98 41 90]]


In [76]:
column_index = 2
column = reshaped_array[:, column_index]
print(column)

column_index = 3
column_sum = reshaped_array[:, column_index].sum() # sum is a method, don't put it behind array name
print(column_sum)

new_column = reshaped_array[:, 2] + reshaped_array[:, 3]
reshaped_array_with_sum = np.column_stack((reshaped_array, new_column))
print(reshaped_array_with_sum)

[17 63 28  9  5]
355
[[ 98  89  17  71  87  34  88]
 [ 20  92  63  87  62  60 150]
 [ 89  79  28  97  44  79 125]
 [ 79  93   9   2  59  65  11]
 [ 22  23   5  98  41  90 103]]


In [82]:
import numpy as np

new_array = np.random.randint(10, 51, size=20) # why size=20? take matrix 5x4 = 20
newest_array = new_array.reshape(5, 4)
print(newest_array)

[[35 28 11 10]
 [16 21 46 23]
 [24 23 23 47]
 [39 37 43 22]
 [39 42 27 14]]


In [96]:
sorted_row = np.sort(newest_array, axis=1)
print(newest_array)

[[35 28 11 10]
 [16 21 46 23]
 [24 23 23 47]
 [39 37 43 22]
 [39 42 27 14]]


In [98]:
columns_sum = np.sum(newest_array, axis=0)
print(columns_sum)

total_array = np.max(newest_array)
print(total_array)

[153 151 150 116]
47
